- name: Install MariaDB package
  yum:
    name:
      - mariadb-server
      - MySQL-python
    state: installed

- name: Create Mysql configuration file
  template: src=templates/my.cnf.j2 dest=/etc/my.cnf

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv=*.*:ALL host='172.20.1.100' state=present

- name: Move db-load-script to db host
  template:
    src: templates/db-load-script.sql.j2
    dest: /tmp/db-load-script.sql

- name: Load Inventory Data
  shell: mysql -f < /tmp/db-load-script.sql
